### ISSUE TITLE
CLI: contract `init` scripts don't understand quotes

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#130]
Given this commit script for the [equitx data_feed contract](https://github.com/EquitXDev/equitxdev/tree/main/contracts/data-feed):

```toml
[development.contracts.data_feed]
client = true
init = """
admin_set --new-admin me
sep40_init --resolution 300000 --assets "[{\"Stellar\": \"$(stellar contract id asset --asset native)\"} ]" --decimals 14 --base "{\"Stellar\":\"$(stellar contract id asset --asset native)\"}"
"""
```

It should run correctly.

Right now, `loam build` doesn't understand the quotes on the `sep40_init` script the right way. The command works when you run it in your terminal, but not when you run it through `loam build` or `loam dev`.
