### ISSUE TITLE
build-clients: in `staging` and `production`, require contracts to be IDs

### ISSUE THREAD

**Issue by chadoh** [loambuild/loam#76]
In [our example `environments.toml` file](https://github.com/loambuild/frontend/blob/main/environments.toml), we imply that `staging` and `production` environments will only allow contracts to be IDs.

```toml
[development.contracts]
soroban-atomic-swap-contract = { workspace = true }

[production.contracts]
soroban-atomic-swap-contract = "C987…"
```

However, right now in our tests, we _only_ check the `production` environment, because that's the default for `loam build`, and we are using `workspace = true` for all the contracts.

We need to update our `environments.toml` parsing to only allow contracts to be strings, in staging and production. And we need to update our tests to check for this, and to make the current tests set `development.contracts` instead, and also set `LOAM_ENV` with them (and/or add the `--env` flag to `cargo build`—it's currently supported by `build_clients.rs`, but not added to `build.rs`, which is the actually-callable command).
